### ISSUE TITLE
[2.1.4] PyPI release tarballs contain compiled .pyc files?

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#494]
**Describe the bug**
Hi @slgobinath, it has [been brought to my attention](https://bugs.gentoo.org/864765) that the SafeEyes PyPI tarballs contain some compiled `.pyc` files. I believe that is an accident and likely points to some problem in the process of making these files. What do you think? Best, Sebastian

**To Reproduce**
```console
# wget -O- https://files.pythonhosted.org/packages/1d/e8/221f5afdb7aba8524496906e1fc7d58bd75fb7cf0b3036392cffcd632eda/safeeyes-2.1.4.tar.gz 2>/dev/null | tar tz | grep '\.pyc$' | sort
safeeyes-2.1.4/safeeyes/plugins/audiblealert/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/audiblealert/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/breakscreen/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/donotdisturb/__pycache__/dependency_checker.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/donotdisturb/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/donotdisturb/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/donotdisturb/__pycache__/validator.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/healthstats/__pycache__/dependency_checker.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/healthstats/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/healthstats/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/healthstats/__pycache__/validator.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/mediacontrol/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/mediacontrol/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/notification/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/notification/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/rpcserver/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/rpcserver/__pycache__/validator.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/screensaver/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/screensaver/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/smartpause/__pycache__/dependency_checker.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/smartpause/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/smartpause/__pycache__/plugin.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/smartpause/__pycache__/validator.cpython-38.pyc
safeeyes-2.1.4/safeeyes/plugins/trayicon/__pycache__/plugin.cpython-310.pyc
safeeyes-2.1.4/safeeyes/plugins/trayicon/__pycache__/plugin.cpython-38.pyc
```

**Expected behavior**
No `.pyc` in source tarballs.

**Desktop (please complete the following information):**
 - OS: n/a
 - Desktop Env: n/a
 - Version: 2.1.4 + earlier releases

**Debug Log**
n/a

**Screenshots**
n/a

**Comment by slgobinath** [comment]
Hi Sebastian,
Yes this is my fault in releasing the last version. I did it in a hurry and didn't verify the content. I will release a new version without the binary files.

Thanks for pointing it out.

**Comment by hartwork** [comment]
@slgobinath thanks for your quick reply. I would like to note that all of 2.1.3, 2.1.2 and 2.1.1 — the ones I checked more — also contain `.pyc` files. Could it be that part of the Python packaging pulls in more than it should every time? How do you create these tarballs? Here's how I create and publish releases myself these days:
```
rm -Rf build *.egg-info/ && python3.11 setup.py sdist bdist_wheel
twine upload --verbose dist/*latest.version.here*
```
Are you doing something similar?

**Comment by hartwork** [comment]
Hi @slgobinath happy new year! Please let me know if I can help with this issue somehow.

**Comment by slgobinath** [comment]
Hi @hartwork ,
Happy New Year! TBH I'm struggling to find time to maintain Safe Eyes and thinking about inviting co-maintainers (or even full-time maintainers). If you are interested, I'm happy to let you take over the whole project.

If it is too much work, I'd appreciate it if you can take over the Python package release. Actually better if I can set up CI/CD to manage the release but with some other projects and a demanding job, I'm unable to find quality time to invest in Safe Eyes.

**Comment by slgobinath** [comment]
Related issue https://github.com/slgobinath/SafeEyes/issues/500

**Comment by hartwork** [comment]
Hi @slgobinath, thanks four your reply. I have too much on my plate already myself, so I'll need to think twice about adding to that, but maybe it makes sense to distinguish between development (that would include new features) and maintenance (mostly fixing bugs and infrastructure) here (…), and to note that I want to replace lone work by live collaboration more. To make a concrete offer: As an experiment, we could meet for 60 minutes in a voice/video call some time to team up on whatever needs to be done safeeyes most at that moment, when you find time to.  My GitHub profile has an e-mail contact if that sounds realistic and interesting.

**Comment by slgobinath** [comment]
That sounds great 👍 I also asked the community if anyone like to take over. Let's wait some time to see if anyone volunteers. After that I will schedule a meeting with you and the future maintainer on what we can do.

Thanks again for all your support.

**Comment by slgobinath** [comment]
Fixed with PyPi 2.1.5 release. I've added CI/CD to release to PyPI so this error shouldn't happen anymore. Let's track how the maintenance will be at https://github.com/slgobinath/SafeEyes/issues/500

**Comment by hartwork** [comment]
@slgobinath cool! :tada:
Bumped to 2.1.5 in Gentoo now at https://github.com/gentoo/gentoo/commit/7b414b66e806f0d8f48c949e35017416e4c9517f .
I didn't know you could `git push` in CI. I wonder why/how it works in detail. Did you read about this somewhere online? Still have the link?

**Comment by slgobinath** [comment]
I figured it out at work after some trial and error. The key is using the token to checkout. https://github.com/slgobinath/SafeEyes/blob/master/.github/workflows/release.yml#L13-L14

Then git push will work without further configuration.

**Comment by hartwork** [comment]
I see, thanks!
