### ISSUE TITLE
Detect fullscreen media playing

### ISSUE THREAD

**Issue by domguard** [slgobinath/SafeEyes#510]
I love Safe Eyes but it would be nice to not bother to stop it before looking at a movie or video fullscreen

If it could detect that (in my case) Firefox or Gnome Videos is playing fullscreen , and treat it like no activity at all that would prevent it to launch in the middle of a movie play.

I use Debian bookworm testing / gnome 43.2

thank you very much for this useful piece of software
Dominique

**Comment by otuva** [comment]
@domguard Isn't this the option what you're looking for? 

![image](https://user-images.githubusercontent.com/67955086/221338088-0ef1bd12-1d52-4722-9e56-aaf2898d275a.png)

**Comment by ekasprzak** [comment]
Should that work in Flatpak version?
I installed xprop tool (as Fedora RPM package), allowed SafeEyes [Flatpak] to have access to "All system files" (filesystem=host), but SafeEyes doesn't detect it:

![image](https://github.com/slgobinath/SafeEyes/assets/25803021/98283bd8-5329-4ff7-9717-95ffcb41cc7a)

**Comment by otuva** [comment]
@ekasprzak 
Yeah, that's weird. Make sure to close all safeeyes processes

A flatpak manifest with xprop installed exists and should be working. I'm planning to roll it after release 2.1.6

You can check it [here](https://github.com/flathub/io.github.slgobinath.SafeEyes/tree/2.1.6-build)

**Comment by otuva** [comment]
@ekasprzak 
new version should be live in flathub. Can you verify if the issue is resolved?

**Comment by domguard** [comment]
Gnome Software has 2.15 flathub version, but GUI does not launch
In journal, it says : gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by otuva** [comment]
@domguard 
Can you update and try again? Current version is 2.1.6

**Comment by domguard** [comment]
I updated directly from flathub, v2.16 but still get
gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
perhaps it's due to my particular setup....

**Comment by otuva** [comment]
Yeah, I couldn't reproduce either on both my machine and a virtual one

**Comment by archisman-panigrahi** [comment]
Is this fixed? Can we close this issue?

**Comment by otuva** [comment]
Yes, it is fixed.
